# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        files: ./src/
-   repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        files: ./src/
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash ./run_tests.sh
        language: system
        pass_filenames: false
        always_run: true
